"""empty message

Revision ID: 616bd50835df
Revises: 43b08b6d8cfb
Create Date: 2024-11-08 11:22:23.586292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616bd50835df'
down_revision = '43b08b6d8cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_estate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_type', sa.String(length=100), nullable=False),
    sa.Column('availability', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('society', sa.String(length=200), nullable=True),
    sa.Column('total_sqft', sa.Float(), nullable=False),
    sa.Column('bath', sa.Integer(), nullable=False),
    sa.Column('balcony', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('real_estate')
    # ### end Alembic commands ###
